

#mp.messaging.incoming.diet-requests.connector=smallrye-in-memory
#mp.messaging.outgoing.diet-responses.connector=smallrye-in-memory


quarkus.langchain4j.ollama.base-url=http://localhost:11434
quarkus.langchain4j.ollama.chat-model.model-id=phi3
quarkus.langchain4j.ollama.timeout=60s

quarkus.datasource.jdbc.url=jdbc:h2:mem:default
quarkus.datasource.db-kind=h2
quarkus.hibernate-orm.database.generation=drop-and-create
